trigger:
  branches:
    include:
      - main
  paths:
    include:
      - bicep/*

pool:
  vmImage: "ubuntu-latest"

variables:
  azureServiceConnection: "your-arm-service-connection-name"
  location: "southeastasia"

stages:
  - stage: Validate
    jobs:
      - job: WhatIf
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: $(azureServiceConnection)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az deployment sub what-if \
                  --location $(location) \
                  --template-file bicep/main.bicep

  - stage: Deploy
    dependsOn: Validate
    jobs:
      - job: DeployBicep
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: $(azureServiceConnection)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az deployment sub create \
                  --location $(location) \
                  --template-file bicep/main.bicep
